### ISSUE TITLE
Deploy to central?

### ISSUE THREAD

**Issue by jeremybourgeois** [bonitasoft/bonita-tomcat-h2-listener#1]
Hi,

Is there any chance you guys could deploy this to central? It would be very useful for a project I am currently working on. :)

Thank you!

**Comment by educhastenier** [comment]
There are pretty many constraints to respect before a maven project can be published to Central, so I don't think we will put it soon.
On the other hand, feel free to use it from the source code, it is easy to build ;-)

**Comment by tbouffard** [comment]
Closing as not used anymore
